// please update required information
export const siteMetadata = {
	title: "Phone Empire | Professional Phone Repair Services",
	author: "Phone Empire",
	headerTitle: "Phone Empire | Professional Phone Repair Services",
	description:
		"Expert phone repair services at Phone Empire. We specialize in fixing smartphones, tablets, and other mobile devices with quality parts and professional service.",
	technologies: [
		"iPhone Repair",
		"Samsung Repair",
		"Screen Replacement",
		"Battery Replacement",
		"Water Damage Repair",
		"Charging Port Repair",
		"Camera Repair",
		"Motherboard Repair",
	],
	keywords: [
		"Phone Empire",
		"Phone Repair",
		"Smartphone Repair",
		"iPhone Repair",
		"Samsung Repair",
		"Mobile Phone Repair",
		"Screen Replacement",
		"Battery Replacement",
		"Phone Repair Shop",
		"Local Phone Repair",
		"Professional Phone Repair",
		"Phone Fix",
		"Cell Phone Repair",
		"Tablet Repair",
		"Phone Repair Service",
		"Mobile Device Repair",
		"Phone Repair Near Me",
		"Phone Repair Expert",
		"Phone Repair Store",
	],
	theme: "system", // system, dark or light
	siteUrl: "https://phoneempire.com", // your website URL
	siteLogo: "/logo.png",
	socialBanner: "/social-banner.jpg", // add social banner in the public folder
	email: "contact@phoneempire.com",
	phone: "+1-555-0123-4567",
	github: "https://github.com/phoneempire",
	twitter: "https://twitter.com/phoneempire",
	linkedin: "https://www.linkedin.com/company/phoneempire",
	locale: "en-US",
	manifest: "/manifest.webmanifest",
	siteName: "Phone Empire",
	category: "Electronics Repair",
	twitterHandle: "@phoneempire",
	twitterId: "1234567890",
	countryName: "United States",
	countryCode: "US",
	personalDescription:
		"Professional phone repair service provider with years of experience in fixing all types of mobile devices.",
	occupation: "Phone Repair Specialist",
	company: "Phone Empire LLC",
	location: "New York, NY",
	occupationDescription:
		"Expert in diagnosing and repairing smartphones, tablets, and other mobile devices",
	language: ["English", "Spanish"],
	areaServed: "New York Metropolitan Area",
	socialLinks: [
		"https://facebook.com/phoneempire",
		"https://twitter.com/phoneempire",
		"https://linkedin.com/company/phoneempire",
		"https://instagram.com/phoneempire",
	],
};
