// please update required information
export const siteMetadata = {
	title: "Faiz Khan | Portfolio",
	author: "Faiz Khan | Portfolio",
	headerTitle: "Faiz Khan | Portfolio",
	description:
		"Explore the portfolio of Faiz Khan, showcasing my skills, projects, and experience as a fullstack developer",
	language: "en-us",
	technologies: [
		"Next.js",
		"React",
		"Typescript",
		"Node.js",
		"TailwindCSS",
		"Python",
		"AWS",
		"GCP",
		"Docker",
		"AI",
	],
	keywords: [
		"Faiz Khan",
		"Next.js",
		"Freelancer",
		"Web Developer",
		"Fullstack Developer",
		"Portfolio",
		"Web Development",
		"Portfolio Website",
		"Blog",
		"Software Development",
		"Personal Website",
		"Software Engineer",
		"React",
		"Typescript",
		"Node.js",
		"Python",
		"MongoDB",
		"TailwindCSS",
		"Express.js",
	],
	theme: "system", // system, dark or light
	siteUrl: "https://faiz-khan.in", // your website URL
	siteLogo: "/sakura.png",
	socialBanner: "/opengraph-image.gif", // add social banner in the public folder
	email: "faizpathan1717@gmail.com",
	github: "https://github.com/fzkhan19",
	twitter: "https://twitter.com/unfaized__",
	linkedin: "https://www.linkedin.com/in/fzkhan19/",
	locale: "en-US",
	manifest: "/manifest.webmanifest",
};
