export const siteMetadata = {
	title: "Kuhn & Partner | Trusted Real Estate Brokers in Los Angeles",
	author: "Kuhn & Partner",
	headerTitle: "Kuhn & Partner | Your Trusted Real Estate Experts",
	description:
		"Kuhn & Partner is your trusted real estate broker in Los Angeles, specializing in buying, selling, and renting properties. Our expert team provides personalized service to help you find your dream home or investment property.",
	technologies: [
		"Property Buying",
		"Property Selling",
		"Real Estate Investment",
		"Luxury Properties",
		"Commercial Real Estate",
		"Residential Real Estate",
		"Property Management",
		"Market Analysis",
	],
	keywords: [
		"Kuhn & Partner",
		"Real Estate Broker Los Angeles",
		"Property Buying",
		"Property Selling",
		"Luxury Real Estate Los Angeles",
		"Commercial Properties Los Angeles",
		"Residential Properties Los Angeles",
		"Real Estate Investment",
		"Property Management",
		"Trusted Real Estate Broker",
		"Real Estate Services",
		"Real Estate Near Me",
		"Real Estate Experts",
		"Real Estate Listings",
		"Real Estate Market",
		"Real Estate Solutions",
		"Real Estate Professionals",
		"Real Estate Company",
	],
	theme: "system", // system, dark or light
	siteUrl: "https://kuhnandpartner.com",
	siteLogo: "/logo.svg",
	socialBanner: "/social-banner.jpg",
	email: "contact@kuhnandpartner.com",
	phone: "+1-555-9876-5432",
	github: "https://github.com/kuhnandpartner",
	twitter: "https://twitter.com/kuhnandpartner",
	linkedin: "https://www.linkedin.com/company/kuhnandpartner",
	locale: "en-US",
	manifest: "/manifest.webmanifest",
	siteName: "Kuhn & Partner Real Estate",
	category: "Real Estate",
	twitterHandle: "@kuhnandpartner",
	twitterId: "9876543210",
	countryName: "United States",
	countryCode: "US",
	personalDescription:
		"Experienced real estate brokers dedicated to helping clients buy, sell, and rent properties with confidence in Los Angeles.",
	occupation: "Real Estate Broker",
	company: "Kuhn & Partner LLC",
	location: "Los Angeles, CA",
	occupationDescription:
		"Experts in real estate transactions, providing personalized service for buying, selling, and renting properties in Los Angeles.",
	language: ["English", "Spanish"],
	areaServed: "Los Angeles Metropolitan Area",
	socialLinks: [
		"https://facebook.com/kuhnandpartner",
		"https://twitter.com/kuhnandpartner",
		"https://linkedin.com/company/kuhnandpartner",
		"https://instagram.com/kuhnandpartner",
	],
};
